FROM registry.docker-cn.com/library/mysql:5.6
MAINTAINER jie <2273828010@qq.com>

RUN set -xe \
  && ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo "Asia/Shanghai" >  /etc/timezone \